DELETE http://localhost:5000/api/auth/delete-account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXMxd3JqNjQwMDAwZXAxd2YwMm9jbXZxIiwiaWF0IjoxNzg1MDgwMDUxLCJleHAiOjE3ODU2ODQ4NTF9.o53hBuer-5SYOhq9XiP8tTaWckVhQ2qZA4ukqxWwD8M