DELETE http://localhost:5000/api/auth/delete-account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXMxeW1kcnowMDAwZXBjbzh2ZnN2b3ZjIiwiaWF0IjoxNzg1MDgyODY0LCJleHAiOjE3ODU2ODc2NjR9.I43h34BR5c70RzdWEE3Jl7h_l7HfuHGSJ0TI8t3jD7k