
### Get all groups 
GET http://localhost:5000/api/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXMyMGM3bm4wMDAwZXBuczVwZHc2cHYxIiwiaWF0IjoxNzg1NTExNTI0LCJleHAiOjE3ODYxMTYzMjR9.tsNRtjnD5B57N2W_rLZVVad-6Dp6KnkAnyS_drFEKlo