PATCH http://localhost:5000/api/users/change-username
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXMyMGM3bm4wMDAwZXBuczVwZHc2cHYxIiwiaWF0IjoxNzg1MDgzMDE4LCJleHAiOjE3ODU2ODc4MTh9.O8Gj0Kg-zms2IT8gpqfQMmFxY7JKIkUBdp4WkUANlFE
Content-Type: application/json

{
  "fullName": "cielo"
}