### Send Message
POST http://localhost:5000/api/chats/cms7k5pdr0008ept4nexl5o65/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXMyMGM3bm4wMDAwZXBuczVwZHc2cHYxIiwiaWF0IjoxNzg1NDg2MDA4LCJleHAiOjE3ODYwOTA4MDh9.54JFO2aP5Ey7TaYJvfWev3Vtxdmej0yfq230UaVWikw
Content-Type: application/json

{
  "content": "hello, fellows blea bela bela this is just a test message!!!"
}